apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-02-18T21:49:24Z"
  generation: 1
  labels:
    app: chartmuseum
    chart: chartmuseum-2.4.0
    heritage: Tiller
    release: helm
  name: helm-chartmuseum
  namespace: devops
  resourceVersion: "10251828"
  selfLink: /apis/apps/v1/namespaces/devops/deployments/helm-chartmuseum
  uid: 6b2bd7fb-c358-42c3-b859-b3305c8f8433
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chartmuseum
      release: helm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chartmuseum
        release: helm
      name: helm-chartmuseum
    spec:
      containers:
      - args:
        - --port=8080
        - --storage-local-rootdir=/storage
        env:
        - name: ALLOW_OVERWRITE
          value: "true"
        - name: CHART_POST_FORM_FIELD_NAME
          value: chart
        - name: DISABLE_METRICS
          value: "true"
        - name: LOG_JSON
          value: "true"
        - name: PROV_POST_FORM_FIELD_NAME
          value: prov
        - name: STORAGE
          value: local
        image: chartmuseum/chartmuseum:v0.8.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: chartmuseum
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: 
            limits:
                ephemeral-storage: 2Gi
            requests:
                ephemeral-storage: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /storage
          name: storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: storage-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-18T21:49:24Z"
    lastUpdateTime: "2020-02-18T21:49:32Z"
    message: ReplicaSet "helm-chartmuseum-7b6594cf95" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-10T18:48:51Z"
    lastUpdateTime: "2020-03-10T18:48:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1