apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2020-03-05T15:37:19Z","generation":2,"labels":{"app.kubernetes.io/component":"jenkins-master","app.kubernetes.io/instance":"jenkins","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"jenkins","helm.sh/chart":"jenkins-1.9.19"},"name":"jenkins","namespace":"devops","resourceVersion":"9948375","selfLink":"/apis/apps/v1/namespaces/devops/deployments/jenkins","uid":"e77ef435-a6f7-40f0-8a95-d1bc351a77b0"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"jenkins-master","app.kubernetes.io/instance":"jenkins"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"checksum/config":"1f814a5adab40fac9a15b8a89e897c070eccf7a5e927d7428427f4fb5448d206"},"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"jenkins-master","app.kubernetes.io/instance":"jenkins","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"jenkins","helm.sh/chart":"jenkins-1.9.19"}},"spec":{"containers":[{"args":["--argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)","--argumentsRealm.roles.$(ADMIN_USER)=admin","--httpPort=8080"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"JAVA_OPTS"},{"name":"JENKINS_OPTS"},{"name":"JENKINS_SLAVE_AGENT_PORT","value":"50000"},{"name":"ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"jenkins-admin-password","name":"jenkins"}}},{"name":"ADMIN_USER","valueFrom":{"secretKeyRef":{"key":"jenkins-admin-user","name":"jenkins"}}}],"image":"jenkins/jenkins:lts","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/login","port":"http","scheme":"HTTP"},"initialDelaySeconds":90,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"jenkins","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"},{"containerPort":50000,"name":"slavelistener","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/login","port":"http","scheme":"HTTP"},"initialDelaySeconds":60,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"cpu":3,"ephemeral-storage":"3Gi","memory":"12Gi"},"requests":{"cpu":"1024m","ephemeral-storage":"1Gi","memory":"4Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/tmp","name":"tmp"},{"mountPath":"/var/jenkins_home","name":"jenkins-home"},{"mountPath":"/var/jenkins_config","name":"jenkins-config","readOnly":true},{"mountPath":"/usr/share/jenkins/ref/secrets/","name":"secrets-dir"},{"mountPath":"/usr/share/jenkins/ref/plugins/","name":"plugin-dir"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["sh","/var/jenkins_config/apply_config.sh"],"env":[{"name":"ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"jenkins-admin-password","name":"jenkins"}}},{"name":"ADMIN_USER","valueFrom":{"secretKeyRef":{"key":"jenkins-admin-user","name":"jenkins"}}}],"image":"jenkins/jenkins:lts","imagePullPolicy":"Always","name":"copy-default-config","resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"50m","memory":"256Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/tmp","name":"tmp"},{"mountPath":"/var/jenkins_home","name":"jenkins-home"},{"mountPath":"/var/jenkins_config","name":"jenkins-config"},{"mountPath":"/usr/share/jenkins/ref/secrets/","name":"secrets-dir"},{"mountPath":"/usr/share/jenkins/ref/plugins","name":"plugins"},{"mountPath":"/var/jenkins_plugins","name":"plugin-dir"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"runAsUser":0},"serviceAccount":"jenkins","serviceAccountName":"jenkins","terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"plugins"},{"emptyDir":{},"name":"tmp"},{"configMap":{"defaultMode":420,"name":"jenkins"},"name":"jenkins-config"},{"emptyDir":{},"name":"secrets-dir"},{"emptyDir":{},"name":"plugin-dir"},{"name":"jenkins-home","persistentVolumeClaim":{"claimName":"jenkins"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-03-05T15:46:07Z","lastUpdateTime":"2020-03-05T15:46:07Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-03-05T15:37:19Z","lastUpdateTime":"2020-03-05T15:46:07Z","message":"ReplicaSet \"jenkins-5846bdc495\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2020-03-05T15:37:19Z"
  generation: 3
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.9.19
  name: jenkins
  namespace: devops
  resourceVersion: "9950047"
  selfLink: /apis/apps/v1/namespaces/devops/deployments/jenkins
  uid: e77ef435-a6f7-40f0-8a95-d1bc351a77b0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: jenkins-master
      app.kubernetes.io/instance: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 1f814a5adab40fac9a15b8a89e897c070eccf7a5e927d7428427f4fb5448d206
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: jenkins-master
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: jenkins
        helm.sh/chart: jenkins-1.9.19
    spec:
      containers:
      - args:
        - --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
        - --argumentsRealm.roles.$(ADMIN_USER)=admin
        - --httpPort=8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: JAVA_OPTS
        - name: JENKINS_OPTS
        - name: JENKINS_SLAVE_AGENT_PORT
          value: "50000"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: jenkins-admin-password
              name: jenkins
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: jenkins-admin-user
              name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: slavelistener
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 3072m
            ephemeral-storage: 3Gi
            memory: 12Gi
          requests:
            cpu: 2048m
            ephemeral-storage: 1Gi
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
          readOnly: true
        - mountPath: /usr/share/jenkins/ref/secrets/
          name: secrets-dir
        - mountPath: /usr/share/jenkins/ref/plugins/
          name: plugin-dir
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - /var/jenkins_config/apply_config.sh
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: jenkins-admin-password
              name: jenkins
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: jenkins-admin-user
              name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        name: copy-default-config
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
        - mountPath: /usr/share/jenkins/ref/secrets/
          name: secrets-dir
        - mountPath: /usr/share/jenkins/ref/plugins
          name: plugins
        - mountPath: /var/jenkins_plugins
          name: plugin-dir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: tmp
      - configMap:
          defaultMode: 420
          name: jenkins
        name: jenkins-config
      - emptyDir: {}
        name: secrets-dir
      - emptyDir: {}
        name: plugin-dir
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-05T16:07:34Z"
    lastUpdateTime: "2020-03-05T16:07:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-05T15:37:19Z"
    lastUpdateTime: "2020-03-05T16:07:34Z"
    message: ReplicaSet "jenkins-6fd777bff6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1