apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    stage: production
    name: database 
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      stage: production
      name: database
      app: postgres
  template:
    metadata:
      labels:
        stage: production
        name: database 
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:latest'
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - name: postgres-5432
              containerPort: 5432
          volumeMounts:
            - name: postgres-disk
              readOnly: false
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-disk
          persistentVolumeClaim:
            claimName: postgres-disk