apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: rodrigogrohl/questcode-backend-user:0.1.2
        ports:
        - containerPort: 3020
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: questcode
              key: NODE_ENV
        - name: MONGO_URI
          #value: "mongodb://dbuser:dbuser18@ds231133.mlab.com:31133/suaaplicacao-dev"
          valueFrom:
              secretKeyRef:
                name: questcode
                key: MONGO_URI
        - name: SECRET_OR_KEY
          value: "b00tc4mp18"