---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mongo-pvc
    namespace: devops
  spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: longhorn
    resources:
      requests:
        storage: 3Gi

---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: devops
    creationTimestamp: null
    name: mongo
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: mongo
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: mongo
      spec:
        containers:
        - image: mongo:4.4.1
          # Repositório oficial - mongo:3
          name: mongo
          resources: {}
          
          volumeMounts:
          - name: mongodb-volume
            mountPath: /data/db
  
        restartPolicy: Always
  
        volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
  status: {}
  
  
  
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: devops
    creationTimestamp: null
    labels:
      service: mongo
    name: mongo
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 27017
      targetPort: 0
    selector:
      service: mongo
  status:
    loadBalancer: {}